-- Run this once after 001_create_products_table.sql.

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique
);

alter table public.categories enable row level security;

create policy "Public can read categories"
  on public.categories for select
  using (true);

create policy "Authenticated users can insert categories"
  on public.categories for insert
  to authenticated
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Authenticated users can delete categories"
  on public.categories for delete
  to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

insert into public.categories (name) values
  ('Sarees'),
  ('Madisars'),
  ('Kurtis');

alter publication supabase_realtime add table public.categories;
